import LatentError.Defs

/-!
# The model assumptions (Section 4) as Lean hypotheses

Unlike `AsymptoticModel` (Ono/AxiomProver), which records the *conclusions* of
Propositions 2–3 as structure fields, here the paper's Assumptions 1–6 themselves are
hypotheses, and those conclusions become theorems to prove (see
`LatentError/Statements/Appendix.lean` and `LatentError/Statements/Main.lean`).

Reading of "conditional on `F`, almost surely as `p → ∞`" (Section 4): the realized
factor path `F` is a fixed matrix satisfying Assumption 6, and the noise array lives on
a probability space `(Ω, μ)` that plays the role of the conditional law of `{Z_il}`
given `F`.  `NoiseModel` is Assumption 2 under that law.  The link from the joint model
(`JointModel`) to this conditional reading, and the tower-property upgrade, are stated in
`LatentError/Statements/Conditional.lean` (`joint_to_conditional`, `tower_upgrade`).

* Assumption 1 (factor moments) only defines `Σ_f`; in the conditional model it is
  the hypothesis `Sf.PosDef`.  Its full probabilistic form is in `JointModel`.
* Assumption 2 → `NoiseModel`.
* Assumptions 3, 4 → fields of `LoadingParams`.
* Assumption 5 → `Assumption5 Sf GB` (kept separate so Theorem 3 can vary `Σ_f`).
* Assumption 6 → `Assumption6 GB F`.
-/

open scoped Matrix Topology MatrixOrder ProbabilityTheory
open Filter MeasureTheory ProbabilityTheory

noncomputable section

namespace PCError

/-- Deterministic loading and noise-variance parameters (Assumptions 3–4, plus the
standing dimension constraints `1 ≤ k < n`). -/
structure LoadingParams (k n : ℕ) where
  /-- Infinite loading array `{B_ij : i ≥ 0, j < k}`; `B⁽ᵖ⁾` is its first `p` rows. -/
  Barr : ℕ → Fin k → ℝ
  /-- Limiting loading Gram `G_B`. -/
  GB : Matrix (Fin k) (Fin k) ℝ
  /-- Average specific variance `δ²`. -/
  δ2 : ℝ
  /-- Conditional variances `δ²_{i,l}` (not depending on `F`). -/
  var : ℕ → Fin n → ℝ
  /-- Uniform conditional fourth-moment bound `κ₄`. -/
  κ4 : ℝ
  hk : 1 ≤ k
  hkn : k < n
  /-- Assumption 2 (positivity of the conditional variances). -/
  var_pos : ∀ i l, 0 < var i l
  /-- Assumption 3: `(1/p) Σ_{i<p} δ²_{i,l} → δ² > 0` for every `l`. -/
  δ2_pos : 0 < δ2
  A3 : ∀ l : Fin n,
    Tendsto (fun p : ℕ => (1 / (p : ℝ)) * ∑ i ∈ Finset.range p, var i l) atTop (𝓝 δ2)
  /-- Assumption 4: `BᵀB/p → G_B` positive definite. -/
  GB_posDef : GB.PosDef
  A4 : Tendsto (fun p : ℕ => GBp Barr p) atTop (𝓝 GB)

/-- Assumption 5: `K = Σ_f^{1/2} G_B Σ_f^{1/2}` has distinct positive eigenvalues
`μ₁ > ⋯ > μ_k > 0`. -/
def Assumption5 {k : ℕ} (Sf GB : Matrix (Fin k) (Fin k) ℝ) : Prop :=
  StrictAnti (sortedEig (Kmat Sf GB)) ∧ ∀ j, 0 < sortedEig (Kmat Sf GB) j

/-- Assumption 6: `W₀ = FᵀG_BF/n` has `k` distinct positive eigenvalues
`λ₁ > ⋯ > λ_k > 0` (necessarily its top `k`, since `rank W₀ ≤ k`). -/
def Assumption6 {k n : ℕ} (GB : Matrix (Fin k) (Fin k) ℝ) (F : Matrix (Fin k) (Fin n) ℝ) :
    Prop :=
  StrictAnti (fun j : Fin k => lam GB F j) ∧ ∀ j : Fin k, 0 < lam GB F j

/-- Assumption 2, under the conditional law of the noise given the factor path: the
entries `Z_{il}` are mutually independent, mean zero, with variance `δ²_{i,l}` and
fourth moment at most `κ₄`. -/
structure NoiseModel (n : ℕ) (var : ℕ → Fin n → ℝ) (κ4 : ℝ)
    (Ω : Type) [MeasurableSpace Ω] (μ : Measure Ω) where
  /-- `Z i l ω = Z_{il}` (0-indexed rows). -/
  Z : ℕ → Fin n → Ω → ℝ
  meas : ∀ i l, Measurable (Z i l)
  indep : iIndepFun (fun il : ℕ × Fin n => Z il.1 il.2) μ
  memLp4 : ∀ i l, MemLp (Z i l) 4 μ
  mean_zero : ∀ i l, μ[Z i l] = 0
  var_eq : ∀ i l, variance (Z i l) μ = var i l
  fourth_le : ∀ i l, μ[fun ω => Z i l ω ^ 4] ≤ κ4

/-- The noise array along one sample path. -/
abbrev NoiseModel.path {n : ℕ} {var : ℕ → Fin n → ℝ} {κ4 : ℝ} {Ω : Type}
    [MeasurableSpace Ω] {μ : Measure Ω} (N : NoiseModel n var κ4 Ω μ) (ω : Ω) :
    ℕ → Fin n → ℝ :=
  fun i l => N.Z i l ω

/-- `σ(F)`, the σ-algebra generated by the factor path `fc a l = f⁽ˡ⁾_a`. -/
def sigmaF {k n : ℕ} {Ω : Type} (fc : Fin k → Fin n → Ω → ℝ) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω a l => fc a l ω) MeasurableSpace.pi

lemma sigmaF_le {k n : ℕ} {Ω : Type} [MeasurableSpace Ω] {fc : Fin k → Fin n → Ω → ℝ}
    (h : ∀ a l, Measurable (fc a l)) : sigmaF fc ≤ ‹MeasurableSpace Ω› :=
  (measurable_pi_iff.mpr fun a => measurable_pi_iff.mpr fun l => h a l).comap_le

/-- The full joint model (Assumptions 1–2 without conditioning), used for Lemma 5 and
for the tower-property upgrade.  `fc a l = f⁽ˡ⁾_a`. -/
structure JointModel (k n : ℕ) (Ω : Type) [MeasurableSpace Ω] [StandardBorelSpace Ω]
    (μ : Measure Ω) [IsProbabilityMeasure μ] where
  Barr : ℕ → Fin k → ℝ
  Sf : Matrix (Fin k) (Fin k) ℝ
  var : ℕ → Fin n → ℝ
  κ4 : ℝ
  fc : Fin k → Fin n → Ω → ℝ
  Z : ℕ → Fin n → Ω → ℝ
  fc_meas : ∀ a l, Measurable (fc a l)
  Z_meas : ∀ i l, Measurable (Z i l)
  /-- Assumption 1. -/
  A1_memLp : ∀ a l, MemLp (fc a l) 2 μ
  A1_mean : ∀ a l, μ[fc a l] = 0
  A1_cov : ∀ a b l, μ[fun ω => fc a l ω * fc b l ω] = Sf a b
  A1_posDef : Sf.PosDef
  /-- Assumption 2, conditional on `σ(F)`. -/
  A2_int4 : ∀ i l, Integrable (fun ω => Z i l ω ^ 4) μ
  A2_indep : iCondIndepFun (sigmaF fc) (sigmaF_le fc_meas)
    (fun il : ℕ × Fin n => Z il.1 il.2) μ
  A2_mean : ∀ i l, μ[Z i l | sigmaF fc] =ᵐ[μ] 0
  A2_var : ∀ i l, μ[fun ω => Z i l ω ^ 2 | sigmaF fc] =ᵐ[μ] fun _ => var i l
  A2_var_pos : ∀ i l, 0 < var i l
  A2_fourth : ∀ i l, μ[fun ω => Z i l ω ^ 4 | sigmaF fc] ≤ᵐ[μ] fun _ => κ4

/-- The realized factor path `F(ω) ∈ ℝ^{k×n}`. -/
abbrev JointModel.F {k n : ℕ} {Ω : Type} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    {μ : Measure Ω} [IsProbabilityMeasure μ] (J : JointModel k n Ω μ) (ω : Ω) :
    Matrix (Fin k) (Fin n) ℝ :=
  Matrix.of fun a l => J.fc a l ω

end PCError

end
